//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalCriminals.Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INationalCriminalService")]
    public interface INationalCriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalService/GenerateSearchResult", ReplyAction="http://tempuri.org/INationalCriminalService/GenerateSearchResultResponse")]
        void GenerateSearchResult(NationalCriminals.ServiceReference1.PersonClientModels model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalService/GenerateSearchResult", ReplyAction="http://tempuri.org/INationalCriminalService/GenerateSearchResultResponse")]
        System.Threading.Tasks.Task GenerateSearchResultAsync(NationalCriminals.ServiceReference1.PersonClientModels model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalCriminalServiceChannel : NationalCriminals.Test.ServiceReference1.INationalCriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalCriminalServiceClient : System.ServiceModel.ClientBase<NationalCriminals.Test.ServiceReference1.INationalCriminalService>, NationalCriminals.Test.ServiceReference1.INationalCriminalService {
        
        public NationalCriminalServiceClient() {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateSearchResult(NationalCriminals.ServiceReference1.PersonClientModels model) {
            base.Channel.GenerateSearchResult(model);
        }
        
        public System.Threading.Tasks.Task GenerateSearchResultAsync(NationalCriminals.ServiceReference1.PersonClientModels model) {
            return base.Channel.GenerateSearchResultAsync(model);
        }
    }
}
