//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalCriminals.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonClientModels", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Models")]
    [System.SerializableAttribute()]
    public partial class PersonClientModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightMinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeMax {
            get {
                return this.AgeMaxField;
            }
            set {
                if ((this.AgeMaxField.Equals(value) != true)) {
                    this.AgeMaxField = value;
                    this.RaisePropertyChanged("AgeMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeMin {
            get {
                return this.AgeMinField;
            }
            set {
                if ((this.AgeMinField.Equals(value) != true)) {
                    this.AgeMinField = value;
                    this.RaisePropertyChanged("AgeMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeightMax {
            get {
                return this.HeightMaxField;
            }
            set {
                if ((this.HeightMaxField.Equals(value) != true)) {
                    this.HeightMaxField = value;
                    this.RaisePropertyChanged("HeightMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeightMin {
            get {
                return this.HeightMinField;
            }
            set {
                if ((this.HeightMinField.Equals(value) != true)) {
                    this.HeightMinField = value;
                    this.RaisePropertyChanged("HeightMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxResult {
            get {
                return this.MaxResultField;
            }
            set {
                if ((this.MaxResultField.Equals(value) != true)) {
                    this.MaxResultField = value;
                    this.RaisePropertyChanged("MaxResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientEmail {
            get {
                return this.RecipientEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientEmailField, value) != true)) {
                    this.RecipientEmailField = value;
                    this.RaisePropertyChanged("RecipientEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeightMax {
            get {
                return this.WeightMaxField;
            }
            set {
                if ((this.WeightMaxField.Equals(value) != true)) {
                    this.WeightMaxField = value;
                    this.RaisePropertyChanged("WeightMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeightMin {
            get {
                return this.WeightMinField;
            }
            set {
                if ((this.WeightMinField.Equals(value) != true)) {
                    this.WeightMinField = value;
                    this.RaisePropertyChanged("WeightMin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INationalCriminalService")]
    public interface INationalCriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalService/GenerateSearchResult", ReplyAction="http://tempuri.org/INationalCriminalService/GenerateSearchResultResponse")]
        string GenerateSearchResult(NationalCriminals.ServiceReference1.PersonClientModels model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCriminalService/GenerateSearchResult", ReplyAction="http://tempuri.org/INationalCriminalService/GenerateSearchResultResponse")]
        System.Threading.Tasks.Task<string> GenerateSearchResultAsync(NationalCriminals.ServiceReference1.PersonClientModels model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalCriminalServiceChannel : NationalCriminals.ServiceReference1.INationalCriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalCriminalServiceClient : System.ServiceModel.ClientBase<NationalCriminals.ServiceReference1.INationalCriminalService>, NationalCriminals.ServiceReference1.INationalCriminalService {
        
        public NationalCriminalServiceClient() {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateSearchResult(NationalCriminals.ServiceReference1.PersonClientModels model) {
            return base.Channel.GenerateSearchResult(model);
        }
        
        public System.Threading.Tasks.Task<string> GenerateSearchResultAsync(NationalCriminals.ServiceReference1.PersonClientModels model) {
            return base.Channel.GenerateSearchResultAsync(model);
        }
    }
}
